# Generated by Django 4.2.16 on 2024-12-03 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="record",
            name="company",
        ),
        migrations.RemoveField(
            model_name="record",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="record",
            name="position",
        ),
        migrations.RemoveField(
            model_name="record",
            name="status",
        ),
        migrations.AddField(
            model_name="record",
            name="birthday",
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="record",
            name="condition",
            field=models.CharField(
                choices=[
                    (
                        "schizophrenia",
                        "Schizophrenia Spectrum and Other Psychotic Disorders",
                    ),
                    ("bipolar", "Bipolar and Related Disorders"),
                    ("depression", "Depressive Disorders"),
                    ("anxiety", "Anxiety Disorders"),
                    ("ocd", "Obsessive Compulsive and Related Disorders"),
                    ("ptsd", "Trauma and Stress Related Disorders"),
                ],
                default="schizophrenia",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="diagnosis",
            field=models.CharField(
                choices=[
                    ("self", "Self-Diagnosed"),
                    ("clinical", "Clinically Diagnosed"),
                    ("evaulation", "Not Diagnosed but Seeking Evaluation"),
                ],
                default="self",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="address",
            field=models.CharField(max_length=100),
        ),
    ]
