# Generated by Django 4.2.16 on 2024-12-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0002_remove_record_company_remove_record_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="insurance",
            field=models.CharField(
                choices=[
                    ("medicare", "Medicare"),
                    ("private", "Private Insurance"),
                    ("none", "No Insurance"),
                ],
                default="none",
                max_length=100,
            ),
        ),
    ]
